### ISSUE TITLE
go方法里面可以不传上下文不

### ISSUE THREAD

**Issue by BenYanYi** [wyjsonGo/GoRouter#37]
GoRouter.getInstance().build("/test/activity").go(this);
go方法里面可以不传上下文不，很多时候调用并不在页面中处理

**Comment by wyjsonGo** [comment]
目前版本是不行的.
之前考虑上下文必传是使用`ARouter`库发现`context`为空的时候在`PretreatmentService.onPretreatment(context, postcard)`方法里就需要判空处理.
还有一点是`ARouter`有初始化`ARouter.init(mApplication)`能保存一下Application,而本库没有初始化方法,有两个在一开始接收application的方法`GoRouter.callAMOnCreate(mApplication)`、`GoRouter.autoLoadRouteModule(mApplication)`不是必须的,所以目前go方法的上线文不能为空.

我下午更新一下,添加一下支持.

**Comment by wyjsonGo** [comment]
已经发布了新版[2.4.5](https://github.com/wyjsonGo/GoRouter/releases/tag/2.4.5)
