### ISSUE TITLE
GoRouter.getInstance().inject(this)问题

### ISSUE THREAD

**Issue by KnightAndroid** [wyjsonGo/GoRouter#39]
你好，我发现一个问题，我将GoRouter.getInstance().inject(this)写在BaseActivity中，发现debug包没问题，正式包崩溃了，是怎么回事呢？

**Comment by wyjsonGo** [comment]
[参考文档8-8](https://github.com/wyjsonGo/GoRouter?tab=readme-ov-file#8--inject%E5%B7%A5%E4%BD%9C%E5%8E%9F%E7%90%86)

**Comment by wyjsonGo** [comment]
使用`GoRouter.getInstance().inject(this)`方法在2.3.2版本之后需要在参数上标记@Keep,在2.3.2版本之前不需要.

主要为了打包优化掉@Param注解,优化掉以后标记的参数会被混淆,`GoRouter.getInstance().inject(this)`方法用的反射,调用出问题,所以需要在参数上标记@Keep.

`GoRouter.getInstance().inject(this)`方法使用反正性能不高,所以在2.3.2版本起，自动生成了参数注入类，内部代码是原生写法，性能更好，使用方法参考文档[4-2](https://github.com/wyjsonGo/GoRouter?tab=readme-ov-file#2--%E8%A7%A3%E6%9E%90%E5%8F%82%E6%95%B0)

**Comment by wyjsonGo** [comment]
使用`GoRouter.getInstance().inject(this)`方法在2.3.2版本之后需要在参数上标记`@Keep`,在2.3.2版本之前不需要.
[参考文档8-7和8-8](https://github.com/wyjsonGo/GoRouter?tab=readme-ov-file#7--%E6%B7%B7%E6%B7%86)

主要为了打包优化掉`@Param`注解,优化掉以后标记的参数会被混淆,`GoRouter.getInstance().inject(this)`方法能内部使用的反射,所以需要在参数上标记`@Keep`.

`GoRouter.getInstance().inject(this)`方法使用反射性能不高,所以在2.3.2版本起，自动生成了参数注入类，内部代码是原生写法，性能更好，使用方法参考文档[4-2](https://github.com/wyjsonGo/GoRouter?tab=readme-ov-file#2--%E8%A7%A3%E6%9E%90%E5%8F%82%E6%95%B0)

**Comment by wyjsonGo** [comment]
@KnightAndroid 

我发布了新版[2.4.6](https://github.com/wyjsonGo/GoRouter/releases/tag/2.4.6)
如果使用了`GoRouter.getInstance().inject(this)`方法，不需要在每个参数上添加`@Keep`标记，只需要在混淆规则里添加下面规则，保护字段
```pro
-keepclassmembers class * {
    @com.wyjson.router.annotation.Param <fields>;
}
```

**Comment by wyjsonGo** [comment]
@KnightAndroid 

我发布了新版[2.4.6](https://github.com/wyjsonGo/GoRouter/releases/tag/2.4.6)
如果使用了`GoRouter.getInstance().inject(this)`方法，不需要在每个参数上添加`@Keep`标记，只需要在混淆规则里添加下面规则，保护字段
```pro
-keepclassmembers class * {
    @com.wyjson.router.annotation.Param <fields>;
}
```
[参考文档8-7](https://github.com/wyjsonGo/GoRouter?tab=readme-ov-file#7--%E6%B7%B7%E6%B7%86)

**Comment by KnightAndroid** [comment]
> @KnightAndroid
> 
> 我发布了新版[2.4.6](https://github.com/wyjsonGo/GoRouter/releases/tag/2.4.6) 如果使用了`GoRouter.getInstance().inject(this)`方法，不需要在每个参数上添加`@Keep`标记，只需要在混淆规则里添加下面规则，保护字段
> 
> ```idl
> -keepclassmembers class * {
>     @com.wyjson.router.annotation.Param <fields>;
> }
> ```
> 
> [参考文档8-7](https://github.com/wyjsonGo/GoRouter?tab=readme-ov-file#7--%E6%B7%B7%E6%B7%86)
好的 收到
