### ISSUE TITLE
inject() method does not get bundle!

### ISSUE THREAD

**Issue by xrn1997** [wyjsonGo/GoRouter#46]
我在父类中使用了GoRouter.getInstance().inject(this)，然后子类中使用@Param(不是所有子类都使用了GoRouter)，运行程序时提示“inject() method does not get bundle!”，我想知道如何解决。

**Comment by xrn1997** [comment]
追加一个问题，当我使用$$Param.inject的时候，一旦这个类被我在gradle中屏蔽了，他就会报错，怎么解决？

**Comment by wyjsonGo** [comment]
目前的版本有两个方案
方案一:在base里加一个开关,有需要的子类重写`isGoRouterInject()`方法返回true

```java
public class BaseParamActivity extends FragmentActivity {

    public boolean isGoRouterInject() {
        return false;
    }

    @Override
    protected void onCreate(@Nullable Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        if (isGoRouterInject()) {
            GoRouter.getInstance().inject(this);
        }
    }
}
```

方案二:给`inject(this)`方法加个`try`

```java
```

**Comment by wyjsonGo** [comment]
目前的版本有两个方案
方案一:在base里加一个开关,有需要的子类重写`isGoRouterInject()`方法返回true

```java
public class BaseParamActivity extends FragmentActivity {

    public boolean isGoRouterInject() {
        return false;
    }

    @Override
    protected void onCreate(@Nullable Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        if (isGoRouterInject()) {
            GoRouter.getInstance().inject(this);
        }
    }
}
```

方案二:给`inject(this)`方法加个`try`

```java
try {
    GoRouter.getInstance().inject(this);
} catch (Exception ignored) {
}
```

我一会发一个新版本,把`inject()`方法不抛`inject() method does not get bundle!`异常信息的版本.

**Comment by wyjsonGo** [comment]
> 追加一个问题，当我使用$$Param.inject的时候，一旦这个类被我在gradle中屏蔽了，他就会报错，怎么解决？

没太理解这句话的意思,生成的`XX$$Param.java`都让你在gradle中屏蔽了.那打包的时候肯定会报错吧?

**Comment by wyjsonGo** [comment]
> 目前的版本有两个方案 方案一:在base里加一个开关,有需要的子类重写`isGoRouterInject()`方法返回true
> 
> ```java
> public class BaseParamActivity extends FragmentActivity {
> 
>     public boolean isGoRouterInject() {
>         return false;
>     }
> 
>     @Override
>     protected void onCreate(@Nullable Bundle savedInstanceState) {
>         super.onCreate(savedInstanceState);
>         if (isGoRouterInject()) {
>             GoRouter.getInstance().inject(this);
>         }
>     }
> }
> ```
> 
> 方案二:给`inject(this)`方法加个`try`
> 
> ```java
> try {
>     GoRouter.getInstance().inject(this);
> } catch (Exception ignored) {
> }
> ```
> 
> 我一会发一个新版本,把`inject()`方法不抛`inject() method does not get bundle!`异常信息的版本.

@xrn1997 已经发布了新版[2.5.1](https://github.com/wyjsonGo/GoRouter/releases/tag/2.5.1),你可以试试.

**Comment by xrn1997** [comment]
> > 追加一个问题，当我使用$$Param.inject的时候，一旦这个类被我在gradle中屏蔽了，他就会报错，怎么解决？
> 
> 没太理解这句话的意思,生成的`XX$$Param.java`都让你在gradle中屏蔽了.如果有调用这个类,那打包的时候肯定会报错吧?

比如说，我在一个模块新建了一个debug文件夹，然后这里面有一个activity使用了GoRouter，并且仅调试的时候使用该文件，当gradle.properties中设置的某个值设为false时，我就排除这个debug文件夹（AndroidManifest也是两份）。之前ARouter是可以这样用的。

**Comment by wyjsonGo** [comment]
> > > 追加一个问题，当我使用$$Param.inject的时候，一旦这个类被我在gradle中屏蔽了，他就会报错，怎么解决？
> > 
> > 
> > 没太理解这句话的意思,生成的`XX$$Param.java`都让你在gradle中屏蔽了.如果有调用这个类,那打包的时候肯定会报错吧?
> 
> 比如说，我在一个模块新建了一个debug文件夹，然后这里面有一个activity使用了GoRouter，并且仅调试的时候使用该文件，当gradle.properties中设置的某个值设为false时，我就排除这个debug文件夹（AndroidManifest也是两份）。之前ARouter是可以这样用的。

理解,我目前项目是这么用的.
![示意](https://github.com/wyjsonGo/GoRouter/assets/5397531/73bdbb11-f459-40b3-b76f-cc1c5483a133)
debug的activity都是一个单独的`module_debug`项目里,在app项目build.gradle里使用`debugApi project(path: ':module_debug')`引用.

你说的这种情况我一会试试,稍后回复你.

**Comment by wyjsonGo** [comment]
我用demo试了一下你所说的情况,我这测试没有问题,debug和release都是可以正常运行和打包的.(如图)
![示意](https://github.com/wyjsonGo/GoRouter/assets/5397531/18837e3a-e315-4560-9561-ef2277f12bc5)
如果你那边有问题的话,我推荐你使用我上面说的那种写法,debug里写的代码肯定是release打包不需要的,所以还是单独创建一个module项目来存放这些类,在app项目里使用`debugApi project(path: ':module_xxx')`或者`debugImplementation project(path: ':module_xxx')`来引用,其他模块通过GoRouter来调用页面和服务.

**Comment by xrn1997** [comment]
> 我用demo试了一下你所说的情况,我这测试没有问题,debug和release都是可以正常运行和打包的.(如图) ![示意](https://private-user-images.githubusercontent.com/5397531/312689820-18837e3a-e315-4560-9561-ef2277f12bc5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA0MTE4NDQsIm5iZiI6MTcxMDQxMTU0NCwicGF0aCI6Ii81Mzk3NTMxLzMxMjY4OTgyMC0xODgzN2UzYS1lMzE1LTQ1NjAtOTU2MS1lZjIyNzdmMTJiYzUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMxNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMTRUMTAxOTA0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NmQwZDlmNjQ1OGIwYTExN2U0NGFhNjgwNGQ2MGNkZmQyMWM5Zjc0ZDU0YmU2M2VlN2E3NzAyYzA0NWVlNDFmOSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.mZn7Tm_6vtmLpVWlZm7bKLyJPrurgcdLgkv1BIkIuxQ) 如果你那边有问题的话,我推荐你使用我上面说的那种写法,debug里写的代码肯定是release打包不需要的,所以还是单独创建一个module项目来存放这些类,在app项目里使用`debugApi project(path: ':module_xxx')`或者`debugImplementation project(path: ':module_xxx')`来引用,其他模块通过GoRouter来调用页面和服务.

![image](https://github.com/wyjsonGo/GoRouter/assets/61549147/dbfc5868-1fa1-409c-bf91-4c94f01328ba)
你看一下，我还是希望这个问题能得到解决。

**Comment by xrn1997** [comment]
> > 我用demo试了一下你所说的情况,我这测试没有问题,debug和release都是可以正常运行和打包的.(如图) ![示意](https://private-user-images.githubusercontent.com/5397531/312689820-18837e3a-e315-4560-9561-ef2277f12bc5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA0MTE4NDQsIm5iZiI6MTcxMDQxMTU0NCwicGF0aCI6Ii81Mzk3NTMxLzMxMjY4OTgyMC0xODgzN2UzYS1lMzE1LTQ1NjAtOTU2MS1lZjIyNzdmMTJiYzUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMxNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMTRUMTAxOTA0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NmQwZDlmNjQ1OGIwYTExN2U0NGFhNjgwNGQ2MGNkZmQyMWM5Zjc0ZDU0YmU2M2VlN2E3NzAyYzA0NWVlNDFmOSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.mZn7Tm_6vtmLpVWlZm7bKLyJPrurgcdLgkv1BIkIuxQ) 如果你那边有问题的话,我推荐你使用我上面说的那种写法,debug里写的代码肯定是release打包不需要的,所以还是单独创建一个module项目来存放这些类,在app项目里使用`debugApi project(path: ':module_xxx')`或者`debugImplementation project(path: ':module_xxx')`来引用,其他模块通过GoRouter来调用页面和服务.
> 
> ![image](https://private-user-images.githubusercontent.com/61549147/312796249-dbfc5868-1fa1-409c-bf91-4c94f01328ba.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA0MTIyMDAsIm5iZiI6MTcxMDQxMTkwMCwicGF0aCI6Ii82MTU0OTE0Ny8zMTI3OTYyNDktZGJmYzU4NjgtMWZhMS00MDljLWJmOTEtNGM5NGYwMTMyOGJhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE0VDEwMjUwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc2NjJkNzJhYjUxNjJjY2Q4NDI2YTlhNDE2NDM4MTQyNzUwMTY1OGU2M2Y2ZDUyMTVmMWM0YTAyMTlkODhkODQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.25wfzsScpI5w0MXncIVqBma3O_Wg70REQm15sVw6cjc) 你看一下，我还是希望这个问题能得到解决。如果你想复现的话，这个项目就在我的仓库里。

**Comment by wyjsonGo** [comment]
> > > 我用demo试了一下你所说的情况,我这测试没有问题,debug和release都是可以正常运行和打包的.(如图) ![示意](https://private-user-images.githubusercontent.com/5397531/312689820-18837e3a-e315-4560-9561-ef2277f12bc5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA0MTE4NDQsIm5iZiI6MTcxMDQxMTU0NCwicGF0aCI6Ii81Mzk3NTMxLzMxMjY4OTgyMC0xODgzN2UzYS1lMzE1LTQ1NjAtOTU2MS1lZjIyNzdmMTJiYzUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMxNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMTRUMTAxOTA0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NmQwZDlmNjQ1OGIwYTExN2U0NGFhNjgwNGQ2MGNkZmQyMWM5Zjc0ZDU0YmU2M2VlN2E3NzAyYzA0NWVlNDFmOSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.mZn7Tm_6vtmLpVWlZm7bKLyJPrurgcdLgkv1BIkIuxQ) 如果你那边有问题的话,我推荐你使用我上面说的那种写法,debug里写的代码肯定是release打包不需要的,所以还是单独创建一个module项目来存放这些类,在app项目里使用`debugApi project(path: ':module_xxx')`或者`debugImplementation project(path: ':module_xxx')`来引用,其他模块通过GoRouter来调用页面和服务.
> > 
> > 
> > ![image](https://private-user-images.githubusercontent.com/61549147/312796249-dbfc5868-1fa1-409c-bf91-4c94f01328ba.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA0MTIyMDAsIm5iZiI6MTcxMDQxMTkwMCwicGF0aCI6Ii82MTU0OTE0Ny8zMTI3OTYyNDktZGJmYzU4NjgtMWZhMS00MDljLWJmOTEtNGM5NGYwMTMyOGJhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE0VDEwMjUwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc2NjJkNzJhYjUxNjJjY2Q4NDI2YTlhNDE2NDM4MTQyNzUwMTY1OGU2M2Y2ZDUyMTVmMWM0YTAyMTlkODhkODQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.25wfzsScpI5w0MXncIVqBma3O_Wg70REQm15sVw6cjc) 你看一下，我还是希望这个问题能得到解决。如果你想复现的话，这个项目就在我的仓库里。

看一下我上面发的图`TestActivity.java`类,加一句这个`@Route(ignoreHelper = true)`.这样就不会生成`TestActivity$$Param.java`类了.自动注入参数使用`GoRouter.getInstance().inject(this)`方法.

**Comment by wyjsonGo** [comment]
> > > 我用demo试了一下你所说的情况,我这测试没有问题,debug和release都是可以正常运行和打包的.(如图) ![示意](https://private-user-images.githubusercontent.com/5397531/312689820-18837e3a-e315-4560-9561-ef2277f12bc5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA0MTE4NDQsIm5iZiI6MTcxMDQxMTU0NCwicGF0aCI6Ii81Mzk3NTMxLzMxMjY4OTgyMC0xODgzN2UzYS1lMzE1LTQ1NjAtOTU2MS1lZjIyNzdmMTJiYzUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMxNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMTRUMTAxOTA0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NmQwZDlmNjQ1OGIwYTExN2U0NGFhNjgwNGQ2MGNkZmQyMWM5Zjc0ZDU0YmU2M2VlN2E3NzAyYzA0NWVlNDFmOSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.mZn7Tm_6vtmLpVWlZm7bKLyJPrurgcdLgkv1BIkIuxQ) 如果你那边有问题的话,我推荐你使用我上面说的那种写法,debug里写的代码肯定是release打包不需要的,所以还是单独创建一个module项目来存放这些类,在app项目里使用`debugApi project(path: ':module_xxx')`或者`debugImplementation project(path: ':module_xxx')`来引用,其他模块通过GoRouter来调用页面和服务.
> > 
> > 
> > ![image](https://private-user-images.githubusercontent.com/61549147/312796249-dbfc5868-1fa1-409c-bf91-4c94f01328ba.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA0MTIyMDAsIm5iZiI6MTcxMDQxMTkwMCwicGF0aCI6Ii82MTU0OTE0Ny8zMTI3OTYyNDktZGJmYzU4NjgtMWZhMS00MDljLWJmOTEtNGM5NGYwMTMyOGJhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE0VDEwMjUwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc2NjJkNzJhYjUxNjJjY2Q4NDI2YTlhNDE2NDM4MTQyNzUwMTY1OGU2M2Y2ZDUyMTVmMWM0YTAyMTlkODhkODQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.25wfzsScpI5w0MXncIVqBma3O_Wg70REQm15sVw6cjc) 你看一下，我还是希望这个问题能得到解决。如果你想复现的话，这个项目就在我的仓库里。

我看你的项目里想实现的是有一个开关,关闭的情况移除debug包路径下的代码,你之前使用ARouter可以,是因为你gradle文件里配置的执行顺序是对的,你会先移除debug包下的类,再去执行ARouter生成帮助类的gradle任务,所以你现在的gradle配置是有问题的,你先执行了GoRouter生成帮助类的任务,再去移除了debug包下的类,所以这就是为什么导致现在报错.
我在demo里按照你的写法是没问题的,你可以在demo里实现一下你想要的测试一下(如图).
![示意](https://github.com/wyjsonGo/GoRouter/assets/5397531/88762507-9a28-4d51-aa53-a4db0f1bf131)

**Comment by wyjsonGo** [comment]
> 不去改gradle配置的话,我按照你项目master分支用ARouter的写法在develop上改了一下可以运行,和你原来用ARouter实现的效果一样 ![示意](https://private-user-images.githubusercontent.com/5397531/312836297-9f726e24-da52-4361-8543-e94a0a85dd3a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA0MjAyMjYsIm5iZiI6MTcxMDQxOTkyNiwicGF0aCI6Ii81Mzk3NTMxLzMxMjgzNjI5Ny05ZjcyNmUyNC1kYTUyLTQzNjEtODU0My1lOTRhMGE4NWRkM2EucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMxNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMTRUMTIzODQ2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZTEwMGFhZmZlYjQzOWI3ZGZjZDkwOTdjMTUzNWFiMjYyNjUyODdjMWVjYzc0YmY1NGNmZjgyODI1MTU2ZDQzMCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.lAnftEap5KwAXpfEt5hys2WIlirvCxUF1eTC9wTi-eg)

我看你原来master分支是这么写的，如果你还是报错，你可以clean一下项目。

**Comment by xrn1997** [comment]
> > 不去改gradle配置的话,我按照你项目master分支用ARouter的写法在develop上改了一下可以运行,和你原来用ARouter实现的效果一样 ![示意](https://private-user-images.githubusercontent.com/5397531/312836297-9f726e24-da52-4361-8543-e94a0a85dd3a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA0MjAyMjYsIm5iZiI6MTcxMDQxOTkyNiwicGF0aCI6Ii81Mzk3NTMxLzMxMjgzNjI5Ny05ZjcyNmUyNC1kYTUyLTQzNjEtODU0My1lOTRhMGE4NWRkM2EucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMxNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMTRUMTIzODQ2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZTEwMGFhZmZlYjQzOWI3ZGZjZDkwOTdjMTUzNWFiMjYyNjUyODdjMWVjYzc0YmY1NGNmZjgyODI1MTU2ZDQzMCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.lAnftEap5KwAXpfEt5hys2WIlirvCxUF1eTC9wTi-eg)
> 
> 我看你原来master分支是这么写的，如果你还是报错，你可以clean一下项目。

多谢指点，我今晚下班试试。

**Comment by wyjsonGo** [comment]
> > > 不去改gradle配置的话,我按照你项目master分支用ARouter的写法在develop上改了一下可以运行,和你原来用ARouter实现的效果一样 ![示意](https://private-user-images.githubusercontent.com/5397531/312836297-9f726e24-da52-4361-8543-e94a0a85dd3a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA0MjAyMjYsIm5iZiI6MTcxMDQxOTkyNiwicGF0aCI6Ii81Mzk3NTMxLzMxMjgzNjI5Ny05ZjcyNmUyNC1kYTUyLTQzNjEtODU0My1lOTRhMGE4NWRkM2EucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMxNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMTRUMTIzODQ2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZTEwMGFhZmZlYjQzOWI3ZGZjZDkwOTdjMTUzNWFiMjYyNjUyODdjMWVjYzc0YmY1NGNmZjgyODI1MTU2ZDQzMCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.lAnftEap5KwAXpfEt5hys2WIlirvCxUF1eTC9wTi-eg)
> > 
> > 
> > 我看你原来master分支是这么写的，如果你还是报错，你可以clean一下项目。
> 
> 不报错了，但是按着ARouter原来的写法，IService无法作为@param注入，应用打开一片空白。

IService无法用@Param注入,这个本库还没有,我有时间加一下这个.

**Comment by SDH-IT-HO** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
mrk-vi, @samuel-x, @nain1987, @evgost, @qq273766764, @brenoalvs, @GregoryTrzonkowski, @imPage, @fbaiesec, @threeloe, @MacroGu, @thepkbadger, @mrober09, @ElvisLoo, @brycemcwilliams, @ZJKGH0930, @jensbrehmen, @A6GibKm, @gioelecer, @krabishe, @haoyifan, @ShaoZeMing, @maxjunjun, @pyrochemist, @tomhar, @dcbcodes, @LiJianfeng0108, @kaulie, @slichen, @wlwr, @itukikikuti, @TRXDOGE, @dyslexictech, @EthanHeilman, @RodolfoSilva, @manastalukdar, @erpuyang, @RRCastilho97, @andacaydin, @zhangkejiang, @zhaodawei, @spikything, @DropB3ar, @ryuhey0123, @pseudozach, @larson-carter, @Hustada, @acefed, @dravenk, @kabirugad
