### ISSUE TITLE
KSP支持

### ISSUE THREAD

**Issue by Payaml** [wyjsonGo/GoRouter#51]
框架很优秀，有KSP的支持计划吗

**Comment by wyjsonGo** [comment]
没有,之前写了一半删除了,KSP需要根据kotlin版本一直更新,需要一直维护要不就不能用了,所以只支持了kapt(稳定,但是慢).
我现在去写go了,所以kotlin只停留在入门,望谅解.

**Comment by wyjsonGo** [comment]
本库还是会一直维护和优化的,我会长期关注Issues

**Comment by Payaml** [comment]
好的，谢谢了
