### ISSUE TITLE
[onLost] There is no route. path[/main/mainActivity]

### ISSUE THREAD

**Issue by MrJokerBoy** [wyjsonGo/GoRouter#52]
您好，我这边使用的新版本 gradle版本8.+ 且使用的kts写法 出现以上问题

**Comment by wyjsonGo** [comment]
你有在Application里调用`GoRouter.autoLoadRouteModule(this);`方法吗,我看错误是没有这个path,可能是没装载路由.

**Comment by MrJokerBoy** [comment]
有的 调用了
<img width="578" alt="Snipaste_2024-05-10_19-30-32" src="https://github.com/wyjsonGo/GoRouter/assets/46705558/1d6d1a3b-e6fe-4e71-9039-c1c729ee81b1">
<img width="1035" alt="image" src="https://github.com/wyjsonGo/GoRouter/assets/46705558/290a1727-ccaa-4f07-95f5-abb072cc15a0">

**Comment by wyjsonGo** [comment]
我看日志走了装载方法,但是没有模块路由装载的日志,你去检查一下模块的build.gradle.kts文件配置,你可以用demo改成kts写法试试,我感觉是你配置的问题.装载的时候没有模块路由产生的.

**Comment by MrJokerBoy** [comment]
只要是model系列的我目前都加入了这个
<img width="621" alt="image" src="https://github.com/wyjsonGo/GoRouter/assets/46705558/54ee05fb-0023-4ef0-a177-538d8e8ca62a">

**Comment by MrJokerBoy** [comment]
> 我看日志走了装载方法,但是没有模块路由装载的日志,你去检查一下模块的build.gradle.kts文件配置,你可以用demo改成kts写法试试,我感觉是你配置的问题.装载的时候没有模块路由产生的.

好的好的，我去换成正常的gradle试试看。

**Comment by MrJokerBoy** [comment]
有的有的 
<img width="568" alt="image" src="https://github.com/wyjsonGo/GoRouter/assets/46705558/8fb2c989-6f06-49a2-9c12-77763fee88fb">
<img width="1151" alt="image" src="https://github.com/wyjsonGo/GoRouter/assets/46705558/00edf1e6-d0ee-42b1-826c-8cbaaea99d38">
版本也是用的现在最新版 2.5.1

**Comment by wyjsonGo** [comment]
> 有的有的 <img alt="image" width="568" src="https://private-user-images.githubusercontent.com/46705558/329573511-8fb2c989-6f06-49a2-9c12-77763fee88fb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUzNDM0NDAsIm5iZiI6MTcxNTM0MzE0MCwicGF0aCI6Ii80NjcwNTU1OC8zMjk1NzM1MTEtOGZiMmM5ODktNmYwNi00OWEyLTljMTItNzc3NjNmZWU4OGZiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTEwVDEyMTIyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNkY2Y0ZWM2ZDFjNTMzNGYzZjcwZjI2ODIzMDE4MTdiNWZiZTY1ZTc3OTZmMmJiMjYzOWFmMTRiNGFlNTY4NGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.2i_BMz7dfAHXRUgHec5YuzMjPa9Puk1HiVHuv0t-lgY"> <img alt="image" width="1151" src="https://private-user-images.githubusercontent.com/46705558/329573560-00edf1e6-d0ee-42b1-826c-8cbaaea99d38.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUzNDM0NDAsIm5iZiI6MTcxNTM0MzE0MCwicGF0aCI6Ii80NjcwNTU1OC8zMjk1NzM1NjAtMDBlZGYxZTYtZDBlZS00MmIxLTgyNmMtOGNiYWFlYTk5ZDM4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTEwVDEyMTIyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM1Zjc2MGQyZjYzMzk5MGYwZWU1ZjdkNzRkZmUyMGZhMmFiZTg3NjlkM2VjZGIxZDhkMGYyMjMwODViM2U2NDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.QMTCiEh0U-4QTldPDvT5y8vbM6A0W-kfHyybDuaJWWI"> 版本也是用的现在最新版 2.5.1

你第一张图里我看第一行已经使用了`kapt(libs.goRouter.compiler)`了,为啥又写了一个`annotationProcessor(libs.goRouter.compiler)`这个重复了吧,你注释一下annotationProcessor这行

**Comment by MrJokerBoy** [comment]
大佬，要不我这边弄一个demo 给您发过去帮我看看吧 ～

**Comment by MrJokerBoy** [comment]
好的好的，我现在去准备一个 感谢大佬了。

**Comment by MrJokerBoy** [comment]
[GoRouterDemo.zip](https://github.com/wyjsonGo/GoRouter/files/15275461/GoRouterDemo.zip)

**Comment by MrJokerBoy** [comment]
大佬，这个是刚刚弄出来的一个demo，麻烦您帮我看看了。

**Comment by wyjsonGo** [comment]
@MrJokerBoy 我刚刚看了一下你的demo,你这个问题和框架没有关系,是你多模块都没有引用到app打包....
我改了一下运行没问题.
![示例](https://github.com/wyjsonGo/GoRouter/assets/5397531/573d64ba-6fdb-40bd-80e2-1b447c83680f)

**Comment by MrJokerBoy** [comment]
感谢感谢，忘记引入了 就引入了lib🤣！！

---- Replied Message ----
| From | ***@***.***> |
| Date | 05/10/2024 22:37 |
| To | wyjsonGo/GoRouter ***@***.***> |
| Cc | Long ***@***.***>,
Mention ***@***.***> |
| Subject | Re: [wyjsonGo/GoRouter] [onLost] There is no route. path[/main/mainActivity] (Issue #52) |

@MrJokerBoy 我刚刚看了一下你的demo,你这个问题和框架没有关系,是你多模块都没有引用到app打包....
我改了一下运行没问题.
***@***.*** (view on web)
