### ISSUE TITLE
拦截超时问题

### ISSUE THREAD

**Issue by jueduiyheng** [wyjsonGo/GoRouter#53]
隔几分钟就会弹出[doInterceptions] [onInterrupt] message:The interceptor processing timed out. 这大概会是什么问题呢,未登入是可以正常拦截的

**Comment by wyjsonGo** [comment]
你需要在你自定义的拦截器里调用`callback.onContinue(card)`或`callback.onInterrupt(card, ...)`方法,以上两种至少需要调用其中一种,否则就会出现上面的提示.
