### ISSUE TITLE
可支持compose UI？

### ISSUE THREAD

**Issue by pandy23** [wyjsonGo/GoRouter#54]
如题，多谢大佬

**Comment by wyjsonGo** [comment]
这是路由库，和UI没啥关系吧。

**Comment by pandy23** [comment]
不好意思是我的描述不清晰，意思是如果项目用纯jetpack compose框架开发的话，如何集成gorouter呢？compose UI用声明式写的，都是方法，但是@Route注解是用在类上的，怎么用呢？

我想到的是在compose外面套一个activity，然后@Route写在activity头上。。不晓得gorouter有没有直接的方式？

**Comment by wyjsonGo** [comment]
![composeUI](https://github.com/user-attachments/assets/46f58012-ee72-44a7-a6b8-2520332c87ec)
按照我的理解，就算是使用Compose UI声明式写法，那也得有Activity，直接标注@Router就可以了，不晓得你的写法是啥样子的。你可以按照你说的外面套一个activity来使用，抱歉没能帮到你。
