### ISSUE TITLE
触发并发修改异常

### ISSUE THREAD

**Issue by HolinB** [wyjsonGo/GoRouter#55]
业务逻辑是A页面注册事件接收，跳转B页面，处理完后返回A页面同时需要取消事件接收，同时触发内部HashMap导致异常
![591730960661_ pic](https://github.com/user-attachments/assets/deada5bc-678a-4b50-b675-24ba935a107d)
![601730960721_ pic](https://github.com/user-attachments/assets/56f2f7e1-a30e-4142-9bbd-80cb1ef4ef68)

**Comment by wyjsonGo** [comment]
我没触发你说的这种情况，不过从报错来看把`HashMap`换成`ConcurrentHashMap `可以解决这个bug。
我发布了新版[2.5.2](https://github.com/wyjsonGo/GoRouter/releases/tag/2.5.2)
